# Generated by Django 5.2.13 on 2026-04-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harmonized_system_codes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="harmonizedsystemcode",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this HS code is active",
                verbose_name="Active",
            ),
        ),
        migrations.AddField(
            model_name="harmonizedsystemcode",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country associated with this HS code",
                max_length=50,
                null=True,
                verbose_name="Country",
            ),
        ),
    ]
